dist: xenial
sudo: required

language: node_js
node_js:
- "8.11.3"

python:
- "3.6"

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- pip install --user cookiecutter
- git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull && ./emsdk install latest && ./emsdk activate latest && . ./emsdk_env.sh && cd ..

script:
- make test

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- cd cookiecutter-empirical-project
- echo "env:\n  global:\n    secure:\nJzR9XxOWodn/WFQpiBC3qY3ePYeGTF/4PD+zryYNze/zubkm+ypGv02kKawj/2LCf05YRXgGPCkX0rj+O4H6PkjkQlKQaKpBswwHbfrKRasZGE36n/G8ENWPNeNgv182SB4hk65ILmVhE4njrgg/WbEjSxygoSopGvOtDiN0agHsk2MWb0SjjZRNj7JIfUnPbtreQiKR+zuREXEu9OzephAdseyy+jghA3zGw7YQvlQgo++GHqVHM+s9scNRmLrINkovN1J8fHbxzq1H9liH4Xueb52xefzgRJynumq5fGv8m5uTwpJcgFLRpZJGAA6aMdrwyVIoKsBCvKZqnmdGyrfl4G9qJr0Dc65uL8J7QeG/PIzsk9kuUgqJdQl9NbeYc4mTUdXbY5IV1h5zPAm4vfUmqjrhE2NBUrAjfEK4+CD1+qFR1coyDdeknNgXteDcEiyP2tCkq1sm/E5e2FDOB6pjPQ5r2nLZHzQF2F4FAFQI/8VBLZMYtwgcT2uJQ6MtYNwNs1ZdH6v7ng67ftH3RQoLXyId0ufl3o/q80QzlZICSyplRAUJj7uXJ6NA39wJChKYXtQ5mPpaaeRhUb8Tm6eIFYuXuHrESCe0xLeC3789+fDVxb8QMn1uOPZ632m9VxIdbMu3EiKplvA8h4JRLKEJ4eEVdXnJtuZEKP4g/Vo=" >> .travis.yml
- cat .travis.yml #for debugging
- make clean
- git init
- git remote add origin https://${GH_TOKEN}@github.com/devosoft/cookiecutter-empirical-project.git > /dev/null 2>&1
- git checkout -b cut-cookie
- git add .
- git commit --message "Travis build ${TRAVIS_BUILD_NUMBER}"
- test ${TRAVIS_BRANCH} = "master" && git push --force --quiet origin cut-cookie

env:
  global:
    secure: JzR9XxOWodn/WFQpiBC3qY3ePYeGTF/4PD+zryYNze/zubkm+ypGv02kKawj/2LCf05YRXgGPCkX0rj+O4H6PkjkQlKQaKpBswwHbfrKRasZGE36n/G8ENWPNeNgv182SB4hk65ILmVhE4njrgg/WbEjSxygoSopGvOtDiN0agHsk2MWb0SjjZRNj7JIfUnPbtreQiKR+zuREXEu9OzephAdseyy+jghA3zGw7YQvlQgo++GHqVHM+s9scNRmLrINkovN1J8fHbxzq1H9liH4Xueb52xefzgRJynumq5fGv8m5uTwpJcgFLRpZJGAA6aMdrwyVIoKsBCvKZqnmdGyrfl4G9qJr0Dc65uL8J7QeG/PIzsk9kuUgqJdQl9NbeYc4mTUdXbY5IV1h5zPAm4vfUmqjrhE2NBUrAjfEK4+CD1+qFR1coyDdeknNgXteDcEiyP2tCkq1sm/E5e2FDOB6pjPQ5r2nLZHzQF2F4FAFQI/8VBLZMYtwgcT2uJQ6MtYNwNs1ZdH6v7ng67ftH3RQoLXyId0ufl3o/q80QzlZICSyplRAUJj7uXJ6NA39wJChKYXtQ5mPpaaeRhUb8Tm6eIFYuXuHrESCe0xLeC3789+fDVxb8QMn1uOPZ632m9VxIdbMu3EiKplvA8h4JRLKEJ4eEVdXnJtuZEKP4g/Vo=
